### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by AdityaKumar2408** [srbmaury/notes#22]
I would like to improve the NavBar and SearchBox of this page.

**Comment by srbmaury** [comment]
@AdityaKumar2408 any comments?

**Comment by AdityaKumar2408** [comment]
@srbmaury I know I took this long. Because of my Semester exams I can't do much for hacktober. It will be over in 2 days. So I request you to please kindly grant me two more days. Please don't unassign me.

**Comment by srbmaury** [comment]
sure no problem.
