### ISSUE TITLE
Registration/login form

### ISSUE THREAD

**Issue by Swastik200** [srbmaury/notes#24]
Creating a login form using html css and JavaScript

**Comment by srbmaury** [comment]
> Creating a login form using html css and JavaScript

How will that help in this project?

**Comment by Swastik200** [comment]
Just a form for users to login to the page

**Comment by srbmaury** [comment]
Login page without any database? So that any random username password works
? Or it is just an extra addition which has no relation to this project ?

**Comment by Swastik200** [comment]
Just an addition
